### ISSUE TITLE
Feature #1: Users can select a Pokemon card game series by clicking on a logo on the main page or search for all cards by the series name or Pokemon name.

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#1]
## 💰 Motivation

Users will want to search for cards by name or series.

## 📐 Plan

Create a header with an input field for the users to begin their search.  Display various series logos on the main section for the user to click on.

## 🖼️ Wireframes

![user can search mobile]
![image](https://user-images.githubusercontent.com/21251594/127207772-5d7e9893-dc31-4ec7-b9da-55d33f96c38f.png)

![user can search desktop]
![image](https://user-images.githubusercontent.com/21251594/127205319-d26648d9-1c6e-4a66-ae00-6035e162b650.png)

## ✅ Task List

- [x] Add a heading with title, subtitle, and search field.
- [x] Add the deck info.
- [x] Call the api to get all pokemon sets.
  - [x] Listen for the load and create DOM elements to display set logos on the main.
  - [x] Store all set names in a global setNames array.
- [x] Add the Next Page link.
- [x] Ensure the page looks nice on both mobile-sized and desktop-sized screens.
- [x] Listen for a click on the next page link.
  - [x] Display the next set on the page.  
  - [x] Set previous set to hidden.
- [x] Make input required.
- [x] Listen for the return on the input event on the search field.
  - [x] If search input matches any name in setNames, call the api to return all cards for that set.
  - [x] Else call the api to return all cards for that pokemon name = input.
  - [x] Listen for the load and create dom elements for the card objects in the response and redirect to cards.html.
  - [x] Reset input field.
  - [x] Console log card objects to check for a good load.
