### ISSUE TITLE
Feature #6: User can delete cards from their deck.

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#11]
## 💰 Motivation

Users can remove cards from their deck.

## 📐 Plan

Listen for delete button click event.  Call remove on DOM element.  Remove element from data.myCards.
## 🖼️ Wireframes

![user can view a card mobile]
![image](https://user-images.githubusercontent.com/21251594/127687818-01d49ee1-d10a-46b6-a57b-11d0dbaa0592.png)

![user can view a card desktop]
![image](https://user-images.githubusercontent.com/21251594/127687740-d77a73dd-9643-4378-8b2a-e577b55c2286.png)

## ✅ Task List

- [x] Create a new view for myCard.
- [x] Add link to Pokemon name.
- [x] Listen for a click on a card in myDeck.
  - [x] Update myCard DOM to match selected card.
  - [x] Switch view to myCard. 
- [x] Create a new view for Pokemon info.
- [x] Listen for a click on the Pokemon name.
  - [x] Call API to get more information on the Pokemon.
  - [x] Add Pokemon info to Pokemon view.
  - [x] Change view to Pokemon.
 - [x] Ensure the page looks good in both mobile and desktop.
 - [x] Cleanup unnecessary code and styling.
