### ISSUE TITLE
Feature #7: User can navigate back and forth with page links

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#13]
## 💰 Motivation

Users can click back, next, and page links to navigate through the list.

## 📐 Plan

Add links for 1 2 3, back, and next.  Only show back if the user is not on the first page.  Only show next if user is not on the last page.
## 🖼️ Wireframes

![user can view a card mobile]
![image](https://user-images.githubusercontent.com/21251594/128434007-4a88fe06-1a32-40d6-97dd-4eeac4e2fca8.png)

![user can view a card desktop]
![image](https://user-images.githubusercontent.com/21251594/128434056-2ac4dfe1-fcbf-4648-9c7d-637866586877.png)

## ✅ Task List

- [x] Add links for 1, 2, 3, next, back
- [x] Listen for clicks on the links.
  - [x] Check the text of the link
  - [x] If text is a number, show that page and hide the rest.
  - [x] If text is next, show the next page.
  - [x] If text is back, show the last page.
  - [x] If on the last page, hide the next link.
  - [x] If on the first page, hide the back link.
 - [x] Fix any bugs in navigation
 - [x] Ensure the links look good in mobile and desktop.
 - [x] Cleanup any unnecessary code or styling.
