### ISSUE TITLE
Refactor to ES6

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#14]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Change all vars to const or let.
- [x] Use arrow functions for callbacks.
- [x] Use string interpolation instead of concatenation.
