### ISSUE TITLE
Feature #2: User can view a list of all cards in the series.

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#3]
## 💰 Motivation

User can view a list of all cards in the series.

## 📐 Plan

Display cards pulled from api calls.

## 🖼️ Wireframes

![user can view cards mobile]
![image](https://user-images.githubusercontent.com/21251594/127386253-a7f10c4b-a36a-4ed7-9515-19475da5ef68.png)

![user can view cards desktop]
![image](https://user-images.githubusercontent.com/21251594/127386159-19bd58da-1448-4766-a622-0f3ae84761cc.png)

## ✅ Task List

- [x] Create cards.html for displaying Pokemon cards.
- [x] Create cards.js for interacting with cards.html.
- [x] Create new dom li elements for items stored in the pokemonCards array.
- [x] Add li elements to cards ul.
- [x] Update header with series logo if a series has been selected.
- [x] Add Next Page link.
- [x] Listen for a click on the Next Page link.
  - [x] Hide current 15 cards.
  - [x] Create DOM elements for the next 15 cards and display. 
- [x] Ensure page looks good in both mobile and desktop.
- [x] Cleanup unnecessary code and styling.
