### ISSUE TITLE
Feature #3: User can add a card to My Deck.

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#5]
## 💰 Motivation

Users can add cards to their deck.  Users will see their cards when they click on My Deck.

## 📐 Plan

Create a data model for My Deck.  Push selected cards onto My Deck.  Display cards in My Deck when user clicks on the link.

## 🖼️ Wireframes

![user can add card mobile]
![image](https://user-images.githubusercontent.com/21251594/127541934-eb75abf5-a6f3-48e6-8c26-9167de8dd2bf.png)

![user can add card desktop]
![image](https://user-images.githubusercontent.com/21251594/127577937-32b66e2f-24c9-440c-8ed7-45581d6bc515.png)

## ✅ Task List

- [x] Add myDeck to data model with an array and pagination.
- [x] When user clicks on a cards, show the card and Add button.
- [x] Listen for a click on the Add button.  
- [x] Push Pokemon card onto myDeck's array in the function callback.
- [x] Display myDeck's array's length next to My Deck link.
- [x] Listen for a click on Back link.
- [x] Return user to previous page in the function callback.
- [x] Ensure the page looks good in both desktop and mobile.
- [x] Clean up any unnecessary code and CSS.
