### ISSUE TITLE
Feature #4: Users can view their card deck

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#7]
## 💰 Motivation

Users can view the cards they added to  My Deck.

## 📐 Plan

Display cards in My Deck when user clicks on the link.

## 🖼️ Wireframes

![user can view their deck mobile]
![image](https://user-images.githubusercontent.com/21251594/127577850-c5114b00-4800-4136-9eef-3db188f8368a.png)

![user can view their deck desktop]
![image](https://user-images.githubusercontent.com/21251594/127577995-e16d93f0-6739-4e81-9db3-081717a51c0b.png)

## ✅ Task List

- [x] Create a new view for My Deck.
  - [x] Listen for click on My Deck
  - [x] Create DOM elements for the first page of cards.
  - [x] Add DOM elements to My Deck UL.
  - [x] Change view to myDeck.
 - [x] Listen for click on Next Page link.
  - [x] Create DOM elements for the next page of cards.
  - [x] Hide previous elements
  - [x] Add new elements to myDeck UL.
 - [x] Ensure pages look good in mobile and desktop.
 - [x] Clean up any unnecessary code and styling.
