### ISSUE TITLE
Feature #5: Users can view a card in their deck

### ISSUE THREAD

**Issue by angeljubilee** [angeljubilee/pokemon-card-collector#9]
## 💰 Motivation

Users can view a card in their deck and click on a link to get more info on the Pokemon.

## 📐 Plan

Create a new a view for myCard.  Add a link for the Pokemon name.   Call API to get more information on the Pokemon.

## 🖼️ Wireframes

![user can remove a card mobile]
![image](https://user-images.githubusercontent.com/21251594/127718019-997b6a28-0f79-405a-9fcf-35381347e115.png)

![user can view a card desktop]
![image](https://user-images.githubusercontent.com/21251594/127718072-7a4eceae-4884-40ff-a58e-f92ab7c4b53f.png)

## ✅ Task List

- [x] Listen for a click on the Remove button.
  - [x] Call remove on the DOM element.
  - [x] Delete the card from data.
 - [x] Fix any bugs.
 - [x] Ensure page and list look nice in both mobile and desktop.
 - [x] Cleanup unnecessary code and styling.
